### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by johnfosteruk** [kevjs1982/eetv-webui#1]
i hope you don't mind me asking  but what do i do to make this work, or is it just WIP?

**Comment by kevjs1982** [comment]
Hi John,

Sorry didn't see this message until today.

You'll need a PHP Web Server installed - you should be able to download the Zip file for the code here (by clicking Download Zip) and put it on your server.
Open config-sample.js, change the IP address to match your EE TV Boxes IP address and save as config.js and it should just work.

If you simply want to watch TV / Recordings on a XBMC or Kodi box try having a look at my XBMC plugin at https://github.com/kevjs1982/xbmcplugins/blob/master/README.md
